### ISSUE TITLE
Failing to parse decimals

### ISSUE THREAD

**Issue by mauricio-repetto** [MichielMag/parse-ingredients#4]
Hi, I'm having issues with numbers with decimals like '0.5 kg sugar'. It parses as 0 and 5, any suggestions on how to add this case to the re expression? very appreciated. Thanks.

**Comment by mauricio-repetto** [comment]
@MichielMag any help? Thanks

**Comment by MichielMag** [comment]
Hey @mauricio-repetto, I just added support for decimals. Good one!

**Comment by mauricio-repetto** [comment]
Thank you so much! :)
